image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: >
      make venv
      make install-dev
      python scripts/prepare_data.py
    command: >
      python scripts/run_experiment.py trainer.gpus=1 data.batch_size=32
